package(default_visibility = ["//visibility:public"])

exports_files([
    "environment.bzl"
])


filegroup(
    name = "distribution",
    srcs = [
        "WORKSPACE",
        "BUILD",
        "environment.bzl",
        "BUILD.template",
        "export.bzl.template",
        "runtime.bzl.template",
    ]
)